/** Resident curriculum. Original teaching synthesis; anatomy review remains pending.
 * Sources support anatomy and study findings. Scene targets name installed atlas
 * identities only; they never stand in for missing vessels, nuclei or function.
 */
const source=(id,title,pmid,evidenceClass,scope)=>({id,title,url:`https://pubmed.ncbi.nlm.nih.gov/${pmid}/`,evidenceClass,scope});
export const RESIDENT_SOURCES={
  R11:source('R11','Giampiccolo et al., 2021 · motor deficits with preserved intraoperative MEPs','33615216','association','Retrospective peri-Rolandic tumour-surgery series with lesion-symptom mapping. Motor deficits could persist despite unchanged MEPs. This supports broader motor assessment, not a diagnosis or recovery guarantee for the hypothetical case.'),
  R1:source('R1','Frigeri et al., 2015 · microsurgical anatomy of the central lobe','25555079','experimental_anatomy','Human cadaveric dissections: precentral/postcentral gyri, paracentral lobule and vascular relationships. The atlas has no vascular layer.'),
  R2:source('R2','Ribas et al., 2018 · microsurgical anatomy of the central core','29271710','experimental_anatomy','Stepwise human dissections of the insula, capsules, basal ganglia and thalamus. Gross atlas meshes illustrate only part of these layered relationships.'),
  R3:source('R3','Kier et al., 2004 · temporal stem, uncinate, IFOF and optic radiation','15140705','experimental_anatomy','Human anatomical dissection correlated with MR imaging. Supports relative temporal-stem anatomy; not a universal surgical distance.'),
  R4:source('R4','Yogarajah et al., 2009 · Meyer’s loop and postoperative visual fields','19460796','association','Control and temporal-resection cohorts studied with tractography and perimetry. Anterior extent and postoperative field loss vary; a template cannot supply an individual margin.'),
  R5:source('R5','Tanriover et al., 2004 · microsurgical anatomy of the insula and Sylvian fissure','15137609','experimental_anatomy','Human microsurgical anatomy of insular gyri, the Sylvian fissure and MCA branches/perforators. Those vessels are discussed, not rendered here.'),
  R6:source('R6','Chernoff et al., 2018 · a neurosurgical case study of speech planning','29569513','association','A longitudinal surgical case involving the left FAT, with a temporal-resection comparison case tested using the same measures. The fluency/naming dissociation in these two cases does not assign an exclusive function or population-level risk to a tract.'),
  R7:source('R7','Chernoff et al., 2019 · sentence planning during stimulation','31210568','functional_measurement','One awake-mapping case: stimulation changed phrase-boundary timing without the same effect on intra-word articulation. The measured sites are not installed in this atlas.'),
  R8:source('R8','Tredici et al., 1982 · restricted capsular lesions and motor localization','7076549','association','CT and clinical observations of restricted internal-capsular lesions support classical motor localization while allowing individual variation. A lesion-based inference is not a resolved fibre map in this atlas.'),
  R9:source('R9','Catani et al., 2012 · short frontal-lobe connections','22209688','experimental_anatomy','Tractography and post-mortem dissection describe FAT relationships with both SMA and pre-SMA. HCP 6mp and 6ma are orientation pointers here, not measured endpoints of this displayed sample.'),
  R10:source('R10','Yim et al., 2013 · corticobulbar distribution in the internal capsule','24034408','reconstruction','Capsular-infarct observations and a separate DTI sample placed corticobulbar relationships more posteriorly than classical genu accounts. Findings depend on level and method; this atlas cannot adjudicate the individual distribution.'),
};

const parcel=(id,label)=>({kind:'parcel',id,label});
const deep=(id,label)=>({kind:'deep',id,label});
const bundle=(id,label)=>({kind:'bundle',id,label});
const cortex=(...ids)=>ids.map(id=>({id,hemi:'follow'}));
const scene=(extra={})=>({side:'follow',bundles:[],ghost:[],regions:[],deep:false,deepRegions:[],surface:.8,camera:{view:'follow',tweenMs:650},durationSec:30,trace:false,network:null,...extra});
const step=(title,text,observe,anatomy,surgical,question,answer,sources,sceneSpec,extra={})=>({
  title,text,observe,anatomy,surgical,question,answer,sources,scene:scene(sceneSpec),regions:null,
  evidenceClass:'atlas',
  notes:`Ask the learner to answer before opening the explanation. Compare the answer with the named structures and the cited method. Teaching point: ${answer}`,
  ...extra,
});
const lesson=(id,title,minutes,summary,goals,steps,{regionCards=['atlasProvenance'],...extra}={})=>({id,title,minutes,summary,goals,steps:steps.map(s=>({...s,regions:s.regions??regionCards})),
  audience:'Neurosurgical residents',reviewStatus:'draft',category:'Regional anatomy',referenceOnly:true,...extra});

const motor=lesson('motor-cst','Central region & descending motor pathways',20,
  'Orient the central region, follow the descending corridor and distinguish cortical, capsular and cerebellar contributions to movement.',
  ['Orient precentral, postcentral and medial frontal regions.','Describe the corona radiata and capsular neighbours.','Explain why motor dysfunction can arise outside area 4.'],[
  step('Find the two banks of the central sulcus',
    'Start with a relationship: the precentral gyrus lies anterior to the central sulcus; the postcentral gyrus lies posterior. The atlas labels 4 and 3b help you compare its two banks.',
    'Use the structure buttons to alternate between 4 and 3b. Rotate slightly toward the vertex and follow their shared central-region relationship; do not try to memorize the parcel outline.',
    ['The central region continues from the lateral gyri onto the medial paracentral lobule.','6d provides premotor context anterior to the central region. These parcel labels subdivide cortex; they are not names for entire gyri.'],
    'In a perirolandic discussion, describe both the cortical bank and the white matter beneath it. A gyrus name alone leaves the subcortical relationship unexplained.',
    'A lesion approaches the central sulcus from anterior. Which cortical bank is encountered first, and how would your anatomical emphasis change for a lesion approaching from posterior?',
    'From anterior, the precentral bank (area 4) is met first, so the primary motor relationship leads the account. From posterior, the postcentral bank (area 3b) is met first and the somatosensory relationship leads. In either case, extend the account into the underlying white matter. The surface relationship helps frame the examination; it does not by itself predict the deficit.',
    ['R1','M1'],{regions:cortex(8,9,54),surface:.92},{regions:['motorParcels','atlasProvenance'],targets:[parcel(8,'4 · precentral'),parcel(9,'3b · postcentral'),parcel(54,'6d · dorsal premotor')]}),
  step('Continue onto the medial motor surface',
    'The medial view brings the paracentral region and supplementary motor territory into the same frame. Compare posterior medial premotor parcel 6mp with the more anterior 6ma and area 4.',
    'Compare 6mp, 6ma and 4 in the medial view, then inspect SCEF on the adjacent supplementary/cingulate territory. Say which way is anterior before describing the relationships.',
    ['6mp and 6ma orient posterior and anterior medial premotor cortex. SCEF adds the adjacent supplementary/cingulate reference, so the medial-frontal account extends beyond two premotor parcels.','Movement initiation and movement execution are distinct clinical observations; a medial frontal deficit need not be explained by destruction of area 4.'],
    'The cited medial frontal surgical series describes postoperative motor deficits after SMA-region resection. Use it to discuss an additional mechanism of impaired movement; recovery in that series is not an individual prognosis.',
    'Why can a medial frontal lesion impair movement even when the precentral cortex is preserved?',
    'Motor control includes medial premotor systems as well as primary motor cortex and descending pathways. A deficit of initiation is one possibility to consider. Its clinical characterization and time course must distinguish it from weakness caused by capsular, cortical or vascular injury.',
    ['R1','M1','M9'],{regions:cortex(55,44,43,8),camera:{view:'medial',tweenMs:650},surface:.92},{regions:['motorParcels'],targets:[parcel(55,'6mp · posterior medial premotor'),parcel(44,'6ma · anterior medial premotor'),parcel(43,'SCEF · supplementary/cingulate'),parcel(8,'4 · precentral')]}),
  step('Follow the fan into a descending corridor',
    'The corticospinal reconstruction changes shape with depth: a broad supratentorial fan converges toward a narrower descending course. Follow that change before adding neighbouring systems.',
    'Trace the displayed CST from its broad superior portion toward its narrow inferior portion. Rotate to an anterior view, then restore the lesson scene and compare the two projections.',
    ['Corona radiata describes the radiating white matter above the capsule; it is a region containing several fibre populations.','The displayed CST sample provides a course to inspect. Its visible endpoints are not proof that each line terminates in the highlighted parcel.'],
    'Depth changes the neighbourhood of a lesion: a superficial white matter relationship is different from a compact deep corridor. A lateral screenshot cannot substitute for evaluating the relationship in multiple planes.',
    'Why can two lesions beneath the same cortical region involve very different white matter relationships?',
    'The pathways fan out superiorly and converge with depth. Their neighbours and compactness therefore change along the course. Describe the level of the lesion as well as the overlying gyrus; the atlas supplies an orientation exercise, not a patient-specific lesion map.',
    ['M4','R2','D2'],{bundles:['CST'],regions:cortex(8),surface:.22},{regions:['cstCandidate','coronaCapsule'],evidenceClass:'reconstruction',targets:[bundle('CST','CST · corticospinal tract'),parcel(8,'4 · precentral')]}),
  step('Motor-related origins extend beyond area 4',
    'A descending system is not adequately described by a single cortical origin. Compare the primary motor, premotor and somatosensory reference parcels around the central region.',
    'Alternate between 4, 6d and 3b. Keep the dim CST in view as a spatial reference, without treating every neighbouring parcel as a verified endpoint of this sample.',
    ['Usuda and colleagues reconstructed descending contributions from several motor-related and somatosensory regions in healthy volunteers.','Their tractography estimates describe one method and cohort; the displayed atlas does not separate those contributions into individual origin-specific bundles.'],
    'A proposed explanation of motor risk should consider premotor and postcentral relationships as well as area 4. Sparing one named parcel does not describe the full motor system.',
    'Does a postcentral origin make a descending streamline a primary motor-cortex fibre?',
    'No. Cortical origin, anatomical course and functional role are different descriptors. A pathway may descend from a somatosensory region without becoming an area-4 origin. This scene lets you compare labels, but does not classify its streamlines by origin.',
    ['M4','M1'],{ghost:['CST'],regions:cortex(8,54,9),surface:.72},{regions:['cstCandidate','motorParcels'],evidenceClass:'reconstruction',targets:[parcel(8,'4 · precentral'),parcel(54,'6d · dorsal premotor'),parcel(9,'3b · postcentral')]}),
  step('Read the posterior limb by its neighbours',
    'The posterior limb of the internal capsule lies between the thalamus medially and the lentiform nucleus laterally. The lentiform nucleus comprises putamen and globus pallidus.',
    'Find thalamus, putamen and pallidum around the descending sample. Use their relative positions to describe the corridor; the internal capsule itself is not a segmented mesh here.',
    ['Putamen is lateral to the pallidum; the capsular corridor is medial to the lentiform complex.','Discuss corticobulbar fibres at the genu and anterior posterior limb as a classical orientation, then contrast the more posterior localization reported by Yim. The ghosted CBT and frontopontine samples compare projection courses; they cannot resolve this difference or individual capsular fibre ordering.'],
    'For a deep lesion, name the grey-matter structures on either side of the white matter relationship. This is more informative than describing a line as simply “near the basal ganglia.”',
    'On a sectional image, a white-matter interval has thalamus medially and pallidum laterally. Identify the capsular relationship and explain what would change in an anterior-limb section.',
    'This is the posterior-limb relationship. The lentiform complex remains lateral, while the medial neighbour in an anterior-limb section is caudate head. Use these grey-matter landmarks to establish the level before discussing the projection fibres within the interval.',
    ['R2','M5','R8','R10','D3'],{bundles:['CST'],ghost:['CPT_F','CBT'],deep:true,deepRegions:['THA','PUT','GP'],regions:cortex(8),surface:.08,camera:{view:'anterior',tweenMs:650}},{regions:['coronaCapsule','corticopontine','striatopallidal'],targets:[deep('THA','Thalamus (gross)'),deep('PUT','Putamen'),deep('GP','Globus pallidus'),bundle('CBT','CBT · corticobulbar tract')]}),
  step('Distinguish anterior from posterior capsule',
    'Moving anteriorly changes the medial neighbour of the capsule from thalamus toward caudate head. The lentiform complex remains lateral. This distinguishes two capsular relationships without relying on colour.',
    'Compare caudate and thalamus while keeping putamen and pallidum visible. Describe the anterior and posterior relationships aloud; do not call every interval the posterior limb.',
    ['The anterior limb is related to caudate head medially; the posterior limb is related to thalamus medially.','The genu is the bend between the limbs. This atlas does not segment that bend or its individual fibre subdivisions.'],
    'The clinical significance of a deep frontal trajectory depends on its position along the capsule, not just its distance from a basal-ganglia outline. Vascular relationships require additional anatomy beyond these meshes.',
    'What changes on the medial side as you move from the anterior to the posterior capsular relationship?',
    'The reference changes from caudate head to thalamus. Keep putamen and pallidum as the lateral reference while changing the viewing angle. The exercise identifies neighbouring structures; it does not identify a safe passage between them.',
    ['R2','D3'],{bundles:['CST'],ghost:['CS_A','CS_S'],deep:true,deepRegions:['CAU','THA','PUT','GP'],surface:.08,camera:{view:'anterior',tweenMs:650}},{regions:['striatopallidal'],targets:[deep('CAU','Caudate nucleus'),deep('THA','Thalamus (gross)'),deep('PUT','Putamen'),deep('GP','Globus pallidus')]}),
  step('Add sensory pathways to the deep region',
    'The thalamus is also a reference for sensory systems. Compare the medial lemniscus and superior thalamic radiation samples with the descending corticospinal course.',
    'Follow ML toward the thalamic region and TR_S toward the cortex. Separate the two named samples; the viewer does not join them across a measured synapse.',
    ['The displayed thalamus is a gross structure, not an atlas of individual relay nuclei.','Anatomical direction is knowledge brought to the image. Neither line colour nor a display sweep identifies afferent versus efferent signalling.'],
    'When discussing a deep sensorimotor deficit, characterize sensation as well as strength. A motor-only bundle selection can hide a neighbouring sensory relationship.',
    'Can a continuous-looking ML–thalamus–cortex arrangement prove a single continuous axon?',
    'No. These are separate atlas objects. Spatial proximity does not establish a synapse, continuity or direction. Use the thalamus to orient the anatomical relay relationship while keeping its nuclei and the individual connections unresolved.',
    ['M6','D2','D3'],{bundles:['ML','TR_S'],ghost:['CST'],deep:true,deepRegions:['THA'],regions:cortex(9,51),surface:.16},{regions:['sensoryReturn','thalamus'],evidenceClass:'reconstruction',targets:[bundle('ML','ML · medial lemniscus'),bundle('TR_S','TR_S · superior thalamic radiation'),deep('THA','Thalamus (gross)')]}),
  step('Distinguish cerebellar input and output routes',
    'Motor coordination also involves cerebellar connections. Compare the middle and superior cerebellar peduncles with the dentatorubrothalamic sample and thalamic reference.',
    'Use the posterior view to identify the two peduncle samples, then follow DRTT toward the thalamic region. The dentate and red nuclei are not represented by meshes.',
    ['The middle cerebellar peduncle belongs to the pontocerebellar input route; the superior peduncle carries major cerebellar output pathways.','The DRTT sample illustrates a different relationship from the descending CST. Its name does not mean that all named nuclei have been rendered.'],
    'The cited paediatric posterior-fossa cohort associated postoperative syndrome with proximal dentatothalamocortical pathway injury. Use that evidence to broaden the anatomical discussion beyond the CST, without predicting an individual outcome.',
    'Which peduncle would you discuss when tracing a major cerebellar output route toward thalamus?',
    'The superior cerebellar peduncle. Contrast it with the middle peduncle in the pontocerebellar input route. These connections participate in a larger system; the separate atlas samples do not form a fully resolved circuit.',
    ['M8','M7','D2'],{bundles:['DRTT','SCP','MCP'],ghost:['CST'],deep:true,deepRegions:['THA'],surface:.1,camera:{view:'posterior',tweenMs:650}},{regions:['cerebellarLoop'],evidenceClass:'reconstruction',targets:[bundle('SCP','SCP · superior cerebellar peduncle'),bundle('MCP','MCP · middle cerebellar peduncle'),bundle('DRTT','DRTT · dentatorubrothalamic tract')]}),
  step('Separate a motor map from a parcel map',
    'Return to area 4. A cortical label helps orientation, but it does not divide this brain into measured hand, foot and mouth territories.',
    'Inspect area 4 and its medial continuation. Explain what an additional functional map would need to contribute; there is no hidden homunculus to reveal in the controls.',
    ['Gordon and colleagues found effector-related regions alternating with regions linked to action control using precision functional MRI.','That organization is a functional finding in other participants. The atlas contour supplies a different kind of boundary.'],
    'An anatomical hypothesis and an individual functional observation should remain separately identifiable when discussing a motor-area lesion. A familiar surface location does not make the missing measurement available.',
    'Would highlighting the upper part of parcel 4 establish the foot representation in an individual?',
    'No. It would establish which portion of a population parcel you chose to display. Identifying an individual functional territory needs an appropriate functional observation; its task and localization must accompany the claim.',
    ['M2','M1'],{regions:cortex(8,55),bundles:['CST'],surface:.82},{regions:['effectorMap'],evidenceClass:'functional_measurement',targets:[parcel(8,'4 · precentral'),parcel(55,'6mp · posterior medial premotor')]}),
  step('Explain a motor deficit at three levels',
    'Build a short anatomical differential: cortical bank, deep projection corridor, and distributed motor control. Use a specific relationship for each explanation.',
    'Compare the area-4 and medial-premotor references, then identify thalamus and putamen around CST. Use Restore lesson scene to return after inspecting a structure.',
    ['At the surface, distinguish primary motor from premotor and postcentral relationships.','At depth, describe capsular neighbours; for coordination or initiation, consider systems beyond a single descending bundle.'],
    'Teaching vignette: a resident attributes every postoperative movement problem to CST injury. Explain what the examination and individual imaging would need to distinguish before accepting that account.',
    'Give one reason a preserved area-4 outline cannot establish preservation of motor function.',
    'The outline says nothing about the state of the underlying descending pathways, adjacent blood supply or connected premotor systems. A useful account specifies the observed deficit and anatomical level, then checks the individual evidence rather than treating an atlas selection as a clinical finding.',
    ['R1','R2','M9','M8','D2'],{regions:cortex(8,55,9),bundles:['CST'],ghost:['DRTT'],deep:true,deepRegions:['THA','PUT'],surface:.2},{evidenceClass:'schematic',targets:[parcel(8,'4 · precentral'),parcel(55,'6mp · posterior medial premotor'),deep('THA','Thalamus (gross)'),deep('PUT','Putamen')]}),
]);

const fatScene=(extra={})=>({side:'L',bundles:['FAT'],regions:[{id:74,hemi:'L'},{id:44,hemi:'L'},{id:55,hemi:'L'}],surface:.2,camera:{view:'left',tweenMs:650},...extra});
const fat=lesson('fat-language','Frontal aslant tract & speech planning',12,
  'Compare lateral and medial frontal anatomy, then use task-specific observations to reason about speech impairment.',
  ['Describe the lateral-to-medial frontal relationship.','Distinguish a frontal association pathway from a descending projection.','Separate speech planning, naming and articulation when interpreting a finding.'],[
  step('Connect lateral and medial frontal references',
    'The frontal aslant tract links posterior inferior frontal and medial superior frontal regions. Its oblique course gives you an anatomical relationship to learn before assigning a function.',
    'Compare parcel 44 with medial premotor references 6ma and 6mp. Inspect the intervening FAT sample from lateral and superior views.',
    ['Anatomical FAT descriptions include SMA and pre-SMA. 6mp and 6ma orient their territories without certifying individual streamline terminations.','This lesson retains the left hemisphere because its language experiments concern the left FAT.'],
    'A frontal lesion may affect a connection between separated cortical regions. Explaining only the nearest gyrus can miss the network relationship under discussion.',
    'Is the FAT principally a frontal-to-temporal or a lateral-to-medial frontal relationship?',
    'A lateral-to-medial frontal relationship. Contrast it with pathways that extend into the temporal lobe. The selected cortical parcels help orient the relationship but are not a measured endpoint map for every rendered line.',
    ['R9','S4','R6','M1'],fatScene(),{evidenceClass:'reconstruction',targets:[parcel(74,'44 · inferior frontal'),parcel(44,'6ma · anterior medial premotor'),parcel(55,'6mp · posterior medial premotor')]}),
  step('Separate an association tract from a projection tract',
    'Add the corticospinal sample as context. FAT stays within a frontal relationship, whereas CST has a long descending course. Crossing on a projection does not make the two bundles continuous.',
    'Inspect FAT and the dim CST from the anterior and lateral directions. Identify which sample descends below the cerebral hemisphere.',
    ['Association fibres relate regions within a hemisphere; projection systems link cortex with subcortical levels.','Two bundles can overlap in a two-dimensional view while following different three-dimensional trajectories.'],
    'For a deep frontal discussion, distinguish speech-related network anatomy from descending motor anatomy rather than using “eloquent white matter” as the only description.',
    'If FAT and CST cross on the screen, what observation helps distinguish crossing from apparent overlap?',
    'Rotate to a second plane and follow each sample away from the intersection. Their trajectories remain separately identified. Even an apparent anatomical crossing does not demonstrate communication between those fibres.',
    ['S4','D2','M4'],fatScene({ghost:['CST']}),{evidenceClass:'reconstruction',targets:[bundle('FAT','FAT · frontal aslant tract'),bundle('CST','CST · corticospinal tract')]}),
  step('Ask which part of speech production changed',
    'Speech fluency is not one operation. Word retrieval, phrase planning and articulation can be examined separately. The cited stimulation case measured phrase-boundary pauses and intra-word timing.',
    'Keep the left FAT visible while stating the task distinction. No stimulation marker is shown: the picture supplies anatomy; the paper supplies the experimental observation.',
    ['In the 2019 case, stimulation prolonged pauses at phrase boundaries without the same effect on intra-word articulation.','An anatomical name alone cannot tell you which behavioural component was disrupted.'],
    'When presenting a language finding, report the task and observed error. “Speech arrest” is too broad to communicate every form of impaired speech production.',
    'Which observation better supports a planning disturbance: delayed phrase starts or uniformly slower articulation inside every word?',
    'Delayed phrase starts match the planning-related distinction examined in that case. The comparison depends on the task and timing measurements; it does not establish an exclusive universal function for the FAT.',
    ['R7'],fatScene(),{evidenceClass:'functional_measurement'}),
  step('Compare fluency with word finding',
    'The clinical account becomes more informative when fluency and lexical retrieval are separated. Chernoff’s longitudinal FAT surgical case was compared with a temporal-resection case using the same measures; their fluency and word-finding changes differed.',
    'Describe the medial–lateral frontal course again, then predict why a naming task and connected speech could reveal different difficulties. Reveal the explanation after committing to a prediction.',
    ['Connected speech requires sequencing words into an utterance; naming an isolated item tests a different task demand.','Cohort correlations and individual postoperative observations support questions to investigate, not a one-to-one tract dictionary.'],
    'A normal result on one language task cannot by itself summarize every language operation relevant to a frontal lesion. Present the observed dissociation rather than an all-or-none label of intact language.',
    'Does preserved naming alone establish that spontaneous sentence production is preserved?',
    'No. The tasks impose different demands. Assessing a proposed planning problem requires observations of sentence production as well as the relevant comparison task. The cited observations motivate that distinction without defining a complete intraoperative protocol.',
    ['R6','S4'],fatScene(),{evidenceClass:'association'}),
  step('Build a task-specific anatomical explanation',
    'Hypothetical case: after a left medial frontal procedure, speech initiation and spontaneous right-sided movement are reduced. Naming and articulation are relatively preserved. Intraoperative motor-evoked potentials (MEPs) remained stable.',
    'Compare lateral 44 with medial 6ma and 6mp to explain the distributed frontal relationship. Keep the vignette separate from the group anatomy on screen.',
    ['Initiation, articulation and force are distinct observations. The pattern raises a medial frontal network question without identifying a single injured tract.','Stable MEPs do not establish preservation of every motor function. The actual lesion, examination and time course determine which explanations remain plausible.'],
    'Compare the FAT and CST relationships learned earlier, then state the individual evidence needed. A familiar medial frontal pattern does not remove the need to assess postoperative complications.',
    'Do preserved MEPs settle the explanation for reduced speech initiation and right-sided movement? What information would change your interpretation?',
    'No. Characterize initiation, articulation and strength separately. A medial frontal network disturbance is one hypothesis; the examination, postoperative imaging and evolution must also assess ischaemia, haemorrhage and other causes. Stable MEPs do not rule out every motor deficit, identify FAT injury or guarantee recovery.',
    ['R6','R7','S4','M9','R11'],fatScene(),{evidenceClass:'schematic',targets:[parcel(74,'44 · inferior frontal'),parcel(44,'6ma · anterior medial premotor'),parcel(55,'6mp · posterior medial premotor')]}),
],{regionCards:['fat']});

const opticScene=(extra={})=>({bundles:['OR'],regions:cortex(1),deep:true,deepRegions:['THA','HIP'],surface:.12,camera:{view:'follow',tweenMs:650},...extra});
const optic=lesson('optic-radiation','Optic radiation & the temporal stem',12,
  'Follow the geniculocalcarine relationship, compare temporal-stem neighbours and reason about a contralateral visual-field deficit.',
  ['Orient thalamic and calcarine reference regions.','Describe the anterior turn and neighbouring temporal pathways.','Relate temporal optic-radiation injury to the visual field without inventing a distance threshold.'],[
  step('Orient the thalamic–occipital relationship',
    'The optic radiation connects the lateral geniculate region with visual cortex around the calcarine sulcus. Here, gross thalamus and HCP parcel V1 provide reference objects at the two ends of that relationship.',
    'Find V1 with the structure button, then compare it with the thalamic mesh and the optic-radiation sample. Use the medial view to orient the occipital reference.',
    ['The geniculocalcarine pathway has a thalamic relay, a long white-matter course and a medial occipital cortical destination.','The lateral geniculate nucleus is not separately segmented inside this gross thalamus; use V1 to orient the calcarine destination.'],
    'For a posterior visual-pathway discussion, name the thalamic, white-matter and cortical levels separately. A field deficit requires localization beyond merely identifying the occipital lobe.',
    'Describe the three anatomical levels you would examine when localizing a retrochiasmal visual-pathway problem along the geniculocalcarine system.',
    'Consider the lateral geniculate relay, the optic radiation along its temporal and posterior course, and visual cortex around the calcarine sulcus. They are separated anatomical levels within one system. The gross thalamic mesh provides orientation here but cannot isolate the geniculate nucleus.',
    ['R3','R4','D3','M1'],opticScene(),{referencePlate:'optic-radiation',targets:[parcel(1,'V1 · primary visual'),deep('THA','Thalamus (gross)'),bundle('OR','OR · optic radiation')]}),
  step('Follow the anterior turn before the posterior course',
    'Meyer’s loop is the anterior sweep of the temporal optic radiation before it turns posteriorly. Learning the bend matters because an occipital destination does not imply a purely posterior course.',
    'Find the most anterior visible turn of this OR sample, then follow it posteriorly. The hippocampus is a medial temporal reference; a temporal-horn surface is not installed.',
    ['Dissection and MR correlation place the loop in a close relationship with the temporal horn.','Nilsson’s small DTI study found variable anterior extent. Those measurements depend on sample and method; a shallow atlas turn may reflect reconstruction or display limitations.'],
    'Anterior temporal and temporal-stem discussions should include the optic radiation even when the occipital lobe is distant from the operative region.',
    'Why can an anterior temporal lesion affect a pathway whose cortical destination is occipital?',
    'Because some optic-radiation fibres sweep anteriorly before turning posteriorly toward visual cortex. Destination alone does not describe the course. The temporal horn is useful anatomical context but cannot be identified as a mesh in this viewer.',
    ['R3','R4','S6'],opticScene(),{referencePlate:'temporal-horn',evidenceClass:'reconstruction',targets:[bundle('OR','OR · optic radiation'),deep('HIP','Hippocampus')]}),
  step('Compare the temporal-stem neighbours',
    'The optic radiation shares the temporal region with association pathways. Add uncinate and inferior fronto-occipital samples and distinguish their courses rather than treating every temporal line as visual.',
    'Follow OR, uncinate and IFOF individually from two views. Describe which reconstruction continues between frontal and occipital regions and which turns between anterior temporal and frontal regions.',
    ['Kier and colleagues correlated temporal-stem dissection with MR anatomy of these neighbouring pathways.','A crowded crossing in the render is a reason to inspect each structure separately, not to infer a common function.'],
    'Temporal-stem pathology can raise both visual and language-related anatomical questions. A single selected bundle gives an incomplete description of the neighbourhood.',
    'Which association pathway in this comparison links anterior temporal and frontal regions?',
    'The uncinate fasciculus. IFOF has a longer frontal–occipital relationship, while OR belongs to the thalamic–visual cortical relationship. Identify each course before making a functional inference.',
    ['R3','D2'],opticScene({ghost:['UF','IFOF']}),{evidenceClass:'experimental_anatomy',targets:[bundle('OR','OR · optic radiation'),bundle('UF','UF · uncinate fasciculus'),bundle('IFOF','IFOF · inferior fronto-occipital fasciculus')]}),
  step('Translate the temporal loop into a field question',
    'A temporal optic-radiation injury raises concern for the contralateral superior visual field. Describe the side of the lesion and the affected field explicitly; the two eyes share the homonymous field relationship.',
    'Identify the displayed hemisphere before answering. For a left temporal-loop injury in the vignette, state the side and quadrant of the expected field concern.',
    ['The cited resection study paired tractography with measured postoperative perimetry.','The range of field loss and loop position varies. Neither a fixed temporal-pole distance nor an atlas screenshot predicts an individual field outcome.'],
    'A visual-pathway presentation should distinguish an anatomical risk hypothesis from a documented deficit on perimetry. Use the actual pre- and postoperative field findings when available.',
    'A left temporal-loop injury classically raises concern for which visual field?',
    'The right superior homonymous field, affecting corresponding parts of both eyes. The extent is not fixed by this vignette or by the template; actual perimetry characterizes the deficit.',
    ['R4'],opticScene(),{evidenceClass:'association'}),
  step('Explain an unexpectedly short loop',
    'Teaching vignette: one reconstruction appears to stop posterior to the anticipated anterior bend. The finding is a discrepancy to investigate, not proof that the pathway is anatomically absent.',
    'Rotate the same sample and change cortical transparency. Restore the lesson view and distinguish a hidden segment from a segment that was never reconstructed.',
    ['Visibility and reconstruction completeness are separate questions.','Acquisition, orientation modelling and extraction choices can change which parts of a pathway appear.'],
    'A short-looking loop should not be used to declare a larger resection margin. Separately, Nimsky’s pre-/intraoperative DTI study documented tract displacement during resection: preoperative location is not fixed intraoperatively. Brain shift does not explain a short static atlas sample; it adds another limitation when interpreting actual surgical anatomy.',
    'If lowering cortical opacity reveals a segment, what changed?',
    'Its visibility changed. No new anatomical evidence was acquired and no fibres were reconstructed by moving the slider. If the segment remains absent, that still requires investigation of reconstruction and selection rather than a conclusion of anatomical absence.',
    ['M10','M11','R4','M12'],opticScene(),{evidenceClass:'reconstruction'}),
],{regionCards:['optic']});

const evidence=lesson('evidence-classes','What the anatomy image can establish',8,
  'Use one region to distinguish a surface landmark, an atlas boundary, a reconstruction and a measured functional observation.',
  ['Identify the object supporting each statement.','Explain why an atlas label and a functional finding answer different questions.'],[
  step('A landmark and a parcel answer different questions',
    'A sulcus describes surface shape. A parcel divides cortex according to an atlas method. The two can be anatomically related without sharing the same boundary.',
    'Compare 4 and 3b around the central region. Describe the surface relationship first, then identify what the parcel contour adds.',
    ['HCP-MMP1 combines several cortical features to define its regions.','A parcel name does not replace a description of gyrus, sulcus, side and surface.'],
    'When presenting a lesion, use atlas terminology alongside individual structural anatomy. A template label should not erase a visible anatomical displacement or an uncertain sulcal identification.',
    'Does a parcel contour certify the exact functional edge of an individual gyrus?',
    'No. It identifies the atlas boundary on this reference surface. Individual functional localization is a separate observation, and the structural gyrus still needs to be identified on the individual anatomy.',
    ['M1','R1'],{regions:cortex(8,9),surface:.92},{regions:['parcels'],targets:[parcel(8,'4 · precentral'),parcel(9,'3b · postcentral')]}),
  step('A plausible course is an anatomical hypothesis',
    'The CST sample provides a three-dimensional trajectory to inspect. Its appearance can support a comparison with expected anatomy, but it does not verify every connection.',
    'Follow the descending sample and identify one spatial observation you can make directly. Then name one claim that would need additional evidence.',
    ['A streamline is a reconstruction from diffusion data, not a histological axon.','The tractography validation challenge found plausible-looking false connections under its tested conditions.'],
    'A neat reconstruction should prompt an anatomical consistency check, including its location and method, rather than ending the assessment.',
    'Which is directly observed here: a rendered descending course or a verified functioning corticospinal connection?',
    'A rendered descending course. Verifying the latter needs evidence beyond this display. The distinction does not make the image useless: it defines the spatial question the image can help you investigate.',
    ['M11','D2'],{bundles:['CST'],regions:cortex(8),surface:.18},{evidenceClass:'reconstruction'}),
  step('Put the task beside a functional claim',
    'A functional observation is tied to a task, modality and population. Saying “this tract is language” discards the distinctions that make an experiment interpretable.',
    'Inspect the left FAT sample, then compare a verbal-fluency correlation with phrase-boundary disruption during stimulation. Neither experiment is being replayed on this brain.',
    ['A cohort association relates measured variables; it does not reproduce a stimulation experiment.','A stimulation finding is task-specific and localized under the study conditions.'],
    'Use precise task descriptions when discussing function near a lesion. A tract name is a starting point for the question, not a replacement for the clinical observation.',
    'Are a fluency correlation and a stimulation-induced planning disruption the same evidence?',
    'No. The first is an association between measurements; the second tests a local perturbation under particular task conditions. Both require their population and method to remain attached to the interpretation.',
    ['S4','R7'],fatScene(),{evidenceClass:'functional_measurement'}),
  step('Construct a statement with the correct scope',
    'Teaching vignette: a report labels a highlighted cortical patch, a nearby tract and a patient’s weakness as one finding. Separate the three observations before interpreting their relationship.',
    'Use the current parcel and pathway to form two separate image descriptions. Add a third sentence stating what an actual clinical examination would contribute.',
    ['The parcel describes reference identity; the streamlines describe reconstructed geometry.','A clinical deficit is an observation about a person. This reference scene contains no such examination.'],
    'A useful case discussion keeps anatomy, reconstruction and function connected in the reasoning while making their sources individually clear.',
    'Complete the three-part account: “The atlas shows…; the reconstruction suggests…; the examination establishes…”',
    'The atlas shows a reference parcel; the reconstruction suggests a spatial pathway relationship; the examination establishes the observed clinical deficit. Whether they explain one another is a further question requiring individual localization and supporting evidence.',
    ['M1','M11','R7'],{regions:cortex(8),bundles:['CST'],surface:.32},{evidenceClass:'schematic'}),
],{category:'Reading the evidence'});

const sampling=lesson('sampling-support','Reading a sparse or incomplete tractogram',8,
  'Distinguish visibility, reconstruction and quantitative support through practical display comparisons.',
  ['Separate hidden anatomy from missing reconstruction.','Explain why displayed line count is not fibre count.','Describe an unresolved tract without declaring it absent.'],[
  step('A hidden segment is not a missing segment',
    'Cortex can obscure the bundle beneath it. Changing transparency is a display experiment: it tests visibility while preserving the reconstruction being viewed.',
    'Open Explore anatomy and change Cortical surface from Defined toward Transparent. Compare the same CST sample, then restore the lesson scene.',
    ['The cortical layer and the pathway are separate display objects.','Showing a previously obscured segment changes what you can see, not the underlying diffusion acquisition.'],
    'Before explaining an apparent interruption biologically, establish whether the segment is hidden by display settings or absent from the reconstruction.',
    'What has been established when a segment appears after changing opacity?',
    'That the previous display obscured it. This isolates a visibility issue. It does not demonstrate new fibres, improved reconstruction accuracy or functional preservation.',
    ['D2','M10'],{bundles:['CST'],regions:cortex(8),surface:.9},{evidenceClass:'schematic'}),
  step('Line count is a sampling choice',
    'A dense bundle can look authoritative even when the apparent density is largely a display choice. Compare the named samples without treating their number of lines as an axon census.',
    'Compare CST and OR as separately identified samples. Read the sampled-path caption and distinguish the displayed population from biological fibre number.',
    ['The installed atlas caps the number of displayed paths per bundle.','A streamline can represent a model trajectory without corresponding one-for-one to an axon.'],
    'Do not use a thicker-looking rendered bundle as a direct explanation of greater functional reserve. A quantitative claim needs an appropriate measurement model.',
    'Does twice as many displayed streamlines mean twice as many axons?',
    'No. Seeding, reconstruction, selection and display sampling affect the count. The atlas caption describes sampled paths; it is not a histological measurement or a measure of functional reserve.',
    ['D2','S8'],{bundles:['CST'],ghost:['OR'],surface:.12},{evidenceClass:'model_metric',targets:[bundle('CST','CST · corticospinal tract'),bundle('OR','OR · optic radiation')]}),
  step('A model weight is not a truth probability',
    'SIFT2 adjusts streamline contributions to make a tractogram agree more closely with a diffusion-derived fibre-density model. That is a different quantity from the chance that a connection is anatomically correct.',
    'Inspect the sample without assigning significance to brightness. State what extra measurement would be needed to make a quantitative claim; no SIFT2 values are installed in this atlas.',
    ['SIFT2 weights belong to a model fit and its tractogram.','The atlas display provides geometry and sampling information, not a probability of functional preservation.'],
    'When a tractogram includes a numerical metric, ask what it measures before incorporating it into a clinical explanation. A familiar-looking score can answer a different question from the one you need.',
    'Can a high SIFT2 weight be read as a high probability that an entire connection is true?',
    'No. It is a model-derived contribution to the fit, not a calibrated connection-truth probability. It also does not measure an individual pathway’s functional integrity. This atlas supplies no such weights to inspect.',
    ['S8'],{bundles:['CST'],surface:.16},{regions:['support'],evidenceClass:'model_metric'}),
  step('Report an unresolved reconstruction honestly',
    'Teaching vignette: a tract is expected anatomically but appears short and sparse. Describe the discrepancy and identify the next kind of evidence needed, without turning absence on screen into absence in the brain.',
    'Inspect OR from two views and alter transparency once. Separate a visibility finding from an unresolved question about the reconstruction.',
    ['Tracking near complex fibre configurations is sensitive to the orientation model and method.','An absent reconstruction can coexist with anatomy or function that requires another form of assessment.'],
    'A useful report says what was reconstructed, where it was incomplete and which limitation remains unresolved. It should not declare tissue expendable from a failed visualization.',
    'What is a better conclusion than “the tract is absent, so there is no risk”?',
    '“The pathway was not adequately demonstrated by this reconstruction.” State the method and discrepancy, then reconcile them with individual structural and functional evidence. The statement preserves uncertainty without hiding the actual observation.',
    ['M10','M11'],{bundles:['OR'],regions:cortex(1),surface:.12},{evidenceClass:'reconstruction'}),
],{category:'Reading the evidence',regionCards:['displaySupport']});

const insulaScene=(extra={})=>({regions:cortex(111,106),deep:true,deepRegions:['PUT','GP'],surface:.14,...extra});
const insula=lesson('interoception','Insula, central core & interoception',12,
  'Orient the buried insular surface and its deep neighbours before considering a proposed interoceptive framework.',
  ['Distinguish anterior and posterior insular references.','Describe the lateral-to-medial relationship with the central core.','Separate visible anatomy from a proposed functional circuit.'],[
  step('Find the insula beneath the opercula',
    'The insula forms a buried cortical surface within the Sylvian region. Frontoorbital, frontoparietal and temporal opercula overlie it; seeing an insular parcel requires understanding that depth relationship.',
    'Select AVI and PoI2 in turn with the cortex transparent. They orient anterior ventral and posterior insular regions; the view is a transparency exercise, not an opercular dissection.',
    ['The central insular sulcus divides an anterior short-gyral region from a posterior long-gyral region.','HCP parcels subdivide the insular cortex differently from the gross gyral description.'],
    'A lateral cortical landmark and a buried insular target are at different depths. Describe the overlying opercular relationship before discussing the deeper anatomy.',
    'Why does an insular parcel fail to behave like a patch on the exposed lateral convexity?',
    'Because the insula is covered by the opercula. The selected parcel belongs to a buried surface. Transparency may help locate it, but does not reproduce the anatomy or exposure of a surgical dissection.',
    ['R5','M1'],insulaScene(),{targets:[parcel(111,'AVI · anterior ventral insula'),parcel(106,'PoI2 · posterior insula')]}),
  step('Orient anterior and posterior insular regions',
    'Gross short and long gyri, atlas parcels and functional descriptions are three different ways to describe insular cortex. Establish anterior and posterior before moving between them.',
    'Compare posterior parcel PoI2 with AVI. Rotate to confirm their relative positions instead of inferring anterior from the screen’s left edge.',
    ['The central insular sulcus is a gross anatomical divider; the short/long-gyral pattern has individual variation.','PoI2 and AVI identify reference parcels, not the outlines of all posterior or anterior gyri.'],
    'An insular-lesion description should specify anterior/posterior and superior/inferior relationships. The single word “insula” hides substantial spatial detail.',
    'Does the AVI label outline all the anterior short insular gyri?',
    'No. It identifies an HCP parcel in anterior ventral insula. Gross gyri and multimodal parcels are different subdivisions. Use both descriptions appropriately without treating one as an exact replacement for the other.',
    ['R5','M1'],insulaScene({regions:cortex(106,111)}),{targets:[parcel(106,'PoI2 · posterior insula'),parcel(111,'AVI · anterior ventral insula')]}),
  step('Place the lentiform complex deeper than insula',
    'The insular surface is the lateral face of the central core. Deep to it lie capsule and claustral layers before the putamen and pallidum; the internal capsule lies further medially.',
    'Compare the insular reference with putamen and pallidum, then locate thalamus medially. The thin capsule layers and claustrum are not separately modelled here.',
    ['From lateral to medial: insular cortex, extreme capsule, claustrum, external capsule, putamen, pallidum, then internal capsule.','Beyond the internal capsule, the medial neighbour changes with anteroposterior level: caudate head anteriorly and thalamus posteriorly.'],
    'A deeper insular extension brings the lentiform and internal-capsular relationships into the discussion. Projection pathways and their blood supply can account for motor consequences beyond a cortical insular description.',
    'Where does the claustrum sit in the sequence from insula to putamen, and which capsule separates it from putamen?',
    'The claustrum lies between the extreme capsule laterally and external capsule medially. The external capsule separates it from putamen. These thin layers are omitted from the render, so use the visible insula and putamen as the outer references for a sequence learned from sectional or dissection anatomy.',
    ['R2','R5','D3'],insulaScene({regions:cortex(106),deepRegions:['PUT','GP','THA'],ghost:['CST'],surface:.08}),{targets:[parcel(106,'PoI2 · posterior insula'),deep('PUT','Putamen'),deep('GP','Globus pallidus'),deep('THA','Thalamus (gross)')]}),
  step('Add a functional framework without inventing a circuit',
    'Interoception concerns internal bodily state. Craig’s framework relates posterior and anterior insular processing to bodily representation and feeling; it is a conceptual account, not a recording played by this atlas.',
    'Compare the anterior and posterior reference parcels, then point out which relay nuclei and connecting edges would be needed to render a specific proposed circuit. They are not installed.',
    ['Gross thalamus cannot substitute for a named relay nucleus such as VMpo.','Mesulam and Mufson’s insular output study used tracers in old-world monkeys. That experimental anatomy is distinct from Craig’s conceptual synthesis and does not establish the same circuit in an individual human.','A sequence of teaching highlights establishes the order of explanation, not neural timing or direction.'],
    'A symptom involving bodily sensation or awareness can motivate an insular-network question. It does not allow an atlas parcel to diagnose the mechanism of an individual symptom.',
    'If the highlight moves from posterior to anterior insula, what has actually moved?',
    'The focus of the explanation. No neural signal has been measured, and no latency, causal sequence or individual connection has been established. The framework and its evidence remain separate from the reference geometry.',
    ['S11','S12','M1','D3'],insulaScene({regions:cortex(106,111),deepRegions:['THA']}),{regions:['body','insula','thalamus'],evidenceClass:'conceptual_model',targets:[parcel(106,'PoI2 · posterior insula'),parcel(111,'AVI · anterior ventral insula'),deep('THA','Thalamus (gross)')]}),
  step('Present an insular lesion in anatomical layers',
    'Hypothetical case: a left insular lesion extends toward the lentiform complex. Picture naming is preserved. Build an anatomical account of the surface, depth and neighbouring systems before interpreting the functional observation.',
    'Start with the insular parcel, identify the opercular relationship, then describe the deep lentiform and capsular neighbourhood. State which of those layers are absent from this render.',
    ['A useful account includes surface, depth and neighbouring systems.','A proposed functional framework can complement that account but does not supply missing vessels, nuclei or tissue planes.'],
    'Medial extension raises projection-pathway and lenticulostriate vascular questions. This atlas has no vascular layer, so the relevant vessels and their relation to the lesion cannot be assessed here. Keep that missing anatomy explicit in the layered case description.',
    'Which missing anatomical and functional observations could change your account of this insular lesion, despite preserved naming?',
    'Establish the lesion’s relationship to the lentiform complex, internal capsule and relevant vessels on individual imaging. Define the language tasks and baseline performance: preserved picture naming does not characterize every language operation. New motor findings would also raise projection-pathway and vascular questions. The atlas has no vessel layer or individual functional map, so those uncertainties remain unresolved here.',
    ['R2','R5','S11','N6'],insulaScene({regions:cortex(111,106),deepRegions:['PUT','GP','THA']}),{evidenceClass:'schematic',targets:[parcel(111,'AVI · anterior ventral insula'),parcel(106,'PoI2 · posterior insula'),deep('PUT','Putamen')]}),
],{regionCards:['insula']});

export const RESIDENT_LESSONS=[motor,fat,optic,insula,evidence,sampling];
