// Original fictional teaching vignettes. No patient data or reproduced figures.
// Evidence supports the discussion, not a diagnosis for the fictional patient.
export const CASE_VERSION='2026-09-12.1';
const source=(id,title,pmid,scope)=>({id,title,url:`https://pubmed.ncbi.nlm.nih.gov/${pmid}/`,scope});
const rubric=(anatomy,mechanisms,evidence,uncertainty)=>[
 {title:'Anatomical relationships',prompt:anatomy},{title:'Competing explanations',prompt:mechanisms},
 {title:'Evidence still needed',prompt:evidence},{title:'Uncertainty',prompt:uncertainty},
];
export const CASES=[
 {
  id:'medial-frontal',fictional:true,title:'When strength is not the whole story',location:'Medial frontal glioma',number:'01',
  summary:'Separate motor initiation, output and the limits of a normal examination.',
  diagram:{label:'Left medial frontal territory',view:'Medial concept diagram',cx:205,cy:120,description:'An illustrative medial frontal focus, anterior to primary motor territory. No actual tumor boundary, measured distance or patient registration is shown.'},
  vignette:'A 46-year-old adult is being discussed after a focal seizure led to the discovery of a presumed left medial frontal glioma. The fictional imaging description places the main abnormality anterior to the paracentral motor territory, with an incompletely characterized deep margin. There is no histomolecular diagnosis yet.',
  known:['Full power is documented on a brief confrontation examination.','The patient reports that starting a sequence of right-hand actions feels slower.','The vignette describes a location, not a registered MRI volume.'],
  unknown:['Detailed assessment of initiation, sequencing and language.','Individual cortical, subcortical and vascular relationships at the deep margin.','Histomolecular diagnosis and the wider clinical assessment.'],
  prompt:'A colleague says: “Power is normal, so the motor system is probably not involved.” Which part of that inference can you support, and which relationships would you investigate before accepting it?',
  explore:['Compare the medial premotor references with area 4. State anterior versus posterior before naming a proposed mechanism.','Inspect the descending-pathway reference separately. A displayed tract cannot establish that the fictional lesion spares an individual motor pathway.'],
  references:[{label:'Medial motor relationships',lesson:'motor-cst',step:1},{label:'Descending pathways',lesson:'motor-cst',step:4},{label:'Medial frontal connections',lesson:'fat-language',step:0}],
  finding:{text:'Additional fictional examination: once prompted, the patient produces sustained force, but spontaneous initiation and alternating hand sequences are slower on the right. The examination is incomplete and no single mechanism has been established.',prompt:'Does this alter your interpretation of normal confrontation power? Explain what you would reconsider, what remains defensible, and what further findings could distinguish the alternatives.'},
  debrief:[
   {title:'Describe the distinction before assigning a label',text:'The new observation invites a distinction between initiating or sequencing an action and producing force once an action begins. It does not establish a syndrome. A useful conference response explains why the initial brief power examination did not settle the question.',sourceIds:[]},
   {title:'Use the medial anatomy as a reference',text:'Published SMA-region glioma cohorts describe postoperative motor and speech changes. They support discussing medial motor systems alongside primary motor and descending pathways. They do not establish the cause of this fictional preoperative finding or predict this individual’s recovery.',sourceIds:['sma']},
   {title:'Keep the alternatives visible',text:'For this exercise, state what additional examination and imaging would help distinguish initiation difficulty from weakness or other causes of slowed performance. Do not turn the schematic separation from area 4 into evidence that subcortical or vascular relationships are preserved.',sourceIds:[]},
   {title:'A defensible response',text:'“The brief strength examination is reassuring about the task tested, but it does not resolve the reported initiation difficulty. I would describe the medial frontal relationships, examine initiation and sequencing more closely, and keep the deep margin and individual functional organization explicitly unresolved.” This is an example of reasoning, not the only acceptable wording.',sourceIds:[]},
  ],
  rubric:rubric('Did I distinguish the medial premotor references, area 4 and descending pathways?','Did I separate an observation from a diagnosis and consider competing explanations?','Did I name specific missing examination and individual imaging information?','Did I avoid declaring functional sparing or forecasting recovery from an atlas?'),
  sources:[source('sma','Resection of supplementary motor area gliomas: revisiting supplementary motor syndrome and the role of the frontal aslant tract','34598138','Retrospective surgical cohort. Postoperative associations do not diagnose preoperative symptoms or provide an individual probability of deficit.')],
 },
 {
  id:'insular',fictional:true,title:'The invisible part of the margin',location:'Insular glioma',number:'02',
  summary:'Account for a vascular relationship that the tract display cannot answer.',
  diagram:{label:'Left insular territory',view:'Lateral projection, opercula omitted',cx:265,cy:185,description:'A projected insular focus. Overlying opercula are omitted for the concept diagram. No vessel course, tumor boundary or safe corridor is encoded.'},
  vignette:'A 39-year-old adult with seizures is being discussed for a presumed left insular glioma. The fictional imaging summary describes a predominantly insular abnormality with a medial component. Everyday conversation and a brief limb examination are unremarkable. There is no complete language assessment or vessel-specific description in the referral.',
  known:['The abnormality is described as insular with medial extension.','No individual vessel reconstruction or intraoperative functional measurements are supplied.','The displayed atlas contains reference tracts and gross deep structures, not the patient’s vascular anatomy.'],
  unknown:['The relationship between the medial component and perforating vessels.','Detailed language findings and individual functional organization.','The lesion’s relationship to deep white matter and the central core.'],
  prompt:'A tract rendering appears to leave a gap along the medial side. How would you explain why that picture alone cannot define a safe margin?',
  explore:['Follow the insula toward the central core; distinguish a named layer from an installed rendered object.','Identify which important relationships remain absent from the display, especially vascular ones.'],
  references:[{label:'Insula and central core',lesson:'interoception',step:1},{label:'Layered relationships',lesson:'interoception',step:2}],
  finding:{text:'The next fictional report states that a vascular review cannot confidently establish whether the medial component remains lateral to the lenticulostriate vessels. The colleague’s proposed “gap” came from sampled tractography and did not include vessels.',prompt:'Revise or defend your margin argument. Separate “not shown”, “not assessed” and “shown to be absent”. What would you ask the conference to clarify?'},
  debrief:[
   {title:'Treat an absent layer as missing evidence',text:'The source display never contained the vascular relationship under discussion. A visible gap between sampled tracts therefore cannot answer the vessel question. The new report identifies uncertainty; it does not prove encasement or a particular operative endpoint.',sourceIds:[]},
   {title:'Connect the anatomical and clinical evidence',text:'Microsurgical studies describe insular arterial relationships. A clinical insular-glioma series specifically examined tumor position relative to lenticulostriate arteries. These are reasons to discuss vascular anatomy independently of tract display; neither makes this reference atlas a patient-specific margin map.',sourceIds:['insula-anatomy','lsa']},
   {title:'Make the request concrete',text:'For this exercise, identify which individual imaging, functional assessment and vessel relationships are missing. Keep cortical, white-matter and vascular evidence distinct. A well-calibrated response can retain the anatomical hypothesis while withdrawing an unsupported safety conclusion.',sourceIds:[]},
   {title:'A defensible response',text:'“The apparent tract gap is a property of the reconstruction shown. The medial vessel relationship is unresolved, so I cannot translate that gap into a margin. I would explicitly ask the team to characterize the missing vascular and deep anatomical relationships and correlate them with the wider functional assessment.”',sourceIds:[]},
  ],
  rubric:rubric('Did I relate the insula, deep white matter and central core without inventing a displayed vascular layer?','Did I distinguish a tract-display limitation from an established anatomical finding?','Did I identify the unresolved perforator relationship and functional assessment?','Did I avoid treating absent streamlines as clearance or uncertainty as proven encasement?'),
  sources:[source('insula-anatomy','Tanriover et al. · Microsurgical anatomy of the insula and sylvian fissure','15137609','Human microsurgical anatomy study. Vascular descriptions support orientation, not universal operative distances.'),source('lsa','Resection of insular gliomas: importance of lenticulostriate artery position','18976071','Clinical series relating tumor and artery position. Its individual imaging is not installed in this atlas.')],
 },
 {
  id:'temporoparietal',fictional:true,title:'Beyond a fluent conversation',location:'Temporoparietal glioma',number:'03',
  summary:'Distinguish language tasks and keep visual pathways in the discussion.',
  diagram:{label:'Left posterior temporal / parietal territory',view:'Lateral concept diagram',cx:365,cy:190,description:'An illustrative posterior temporal/parietal focus. It is not an MRI, retinotopic map or depiction of tract displacement.'},
  vignette:'A 52-year-old adult is referred with seizures and a presumed left posterior temporal glioma extending toward inferior parietal white matter. The patient speaks fluently during a brief conversation. No structured language profile or formal visual-field assessment accompanies the referral.',
  known:['Conversational fluency was observed during a short encounter.','The location is described in words; there are no individual functional maps.','The atlas references illustrate language-route hypotheses and visual-pathway anatomy separately.'],
  unknown:['Performance across naming, repetition and comprehension tasks.','Formal visual-field findings.','Individual tumor, cortex and white-matter relationships.'],
  prompt:'The referral describes language as “intact”. What does the reported observation actually establish, and what would you want characterized before presenting the functional relationships?',
  explore:['Compare dorsal and ventral language references. Explain which task each cited experiment investigated.','Inspect the optic-radiation lesson as a separate relationship; do not infer a visual field from the fictional lesion symbol.'],
  references:[{label:'Dorsal language routes',lesson:'language-networks',step:1},{label:'Ventral language routes',lesson:'language-networks',step:2},{label:'Optic-radiation relationships',lesson:'optic-radiation',step:1}],
  finding:{text:'Additional fictional testing reports disproportionate difficulty repeating unfamiliar sound sequences, with better performance on the sampled single-word comprehension tasks. Formal visual-field testing is still unavailable. This is a limited task profile, not an isolated-tract diagnosis.',prompt:'How does the task profile change the conference discussion? State both the pathway hypothesis it may motivate and the conclusions it cannot support.'},
  debrief:[
   {title:'Replace the global label with the measured tasks',text:'Fluent conversation and performance on a structured repetition task are different observations. The new information makes the phrase “language intact” insufficiently specific. It does not establish that any other language function is normal.',sourceIds:[]},
   {title:'Use a pathway hypothesis, not a tract diagnosis',text:'Saur and colleagues combined task fMRI and tractography to investigate repetition and comprehension routes. Their task-based dorsal/ventral account offers a framework for discussion. It does not turn this fictional task profile into proof of an isolated fascicle lesion.',sourceIds:['language']},
   {title:'Keep vision as an independent unanswered question',text:'Work on temporal-resection cohorts combined tractography with visual-field outcomes and described variation in Meyer’s loop. It supports keeping visual function and individual anatomy in the assessment, not transferring a temporal-surgery risk estimate to this fictional temporoparietal case.',sourceIds:['vision']},
   {title:'A defensible response',text:'“Conversation was fluent, but the added testing identifies a task-specific difficulty that deserves a more precise language description. I would use dorsal and ventral references to frame hypotheses, correlate them with individual evidence, and keep the unassessed visual field explicit rather than inferring it from the schematic.”',sourceIds:[]},
  ],
  rubric:rubric('Did I discuss language pathways and visual pathways as distinct relationships?','Did I treat the task profile as a hypothesis-generating observation rather than a fascicle diagnosis?','Did I name missing language tasks, visual-field assessment and individual localization?','Did I avoid equating fluent conversation, parcel identity or template tracts with preserved function?'),
  sources:[source('language','Saur et al. · Ventral and dorsal pathways for language','19004769','Task fMRI and tractography. Functional route hypotheses are task-dependent and are not interchangeable with each named atlas bundle.'),source('vision','Yogarajah et al. · Defining Meyer’s loop: temporal-lobe resections, visual fields and tractography','19460796','Control and temporal-resection cohorts; anatomical variation and postoperative field outcomes. Not a study of this fictional tumor or its individual risk.')],
 },
];
