// Original fictional teaching vignettes. No patient data or reproduced figures.
// Evidence supports the discussion, not a diagnosis for the fictional patient.
export const CASE_VERSION='2026-09-12.1';
const source=(id,title,pmid,scope)=>({id,title,url:`https://pubmed.ncbi.nlm.nih.gov/${pmid}/`,scope});
const rubric=(anatomy,mechanisms,evidence,uncertainty)=>[
 {title:'Anatomical relationships',prompt:anatomy},{title:'Competing explanations',prompt:mechanisms},
 {title:'Evidence still needed',prompt:evidence},{title:'Uncertainty',prompt:uncertainty},
];
export const CASES=[
 {
  id:'medial-frontal',fictional:true,title:'When strength is not the whole story',location:'Medial frontal glioma',number:'01',
  summary:'Separate motor initiation, output and the limits of a normal examination.',
  diagram:{label:'Left medial frontal territory',view:'Medial concept diagram',cx:205,cy:120,description:'An illustrative medial frontal focus, anterior to primary motor territory. No actual tumor boundary, measured distance or patient registration is shown.'},
  vignette:'A 46-year-old adult is being discussed after a focal seizure led to the discovery of a presumed left medial frontal glioma. The fictional imaging description places the main abnormality anterior to the paracentral motor territory, with an incompletely characterized deep margin. There is no histomolecular diagnosis yet.',
  known:['Full power is documented on a brief confrontation examination.','The patient reports that starting a sequence of right-hand actions feels slower.','The vignette describes a location, not a registered MRI volume.'],
  unknown:['Detailed assessment of initiation, sequencing and language.','Individual cortical, subcortical and vascular relationships at the deep margin.','Histomolecular diagnosis and the wider clinical assessment.'],
  prompt:'A colleague says: “Power is normal, so the motor system is probably not involved.” Which part of that inference can you support, and which relationships would you investigate before accepting it?',
  explore:['Compare the medial premotor references with area 4. State anterior versus posterior before naming a proposed mechanism.','Inspect the descending-pathway reference separately. A displayed tract cannot establish that the fictional lesion spares an individual motor pathway.'],
  references:[{label:'Medial motor relationships',lesson:'motor-cst',step:1},{label:'Descending pathways',lesson:'motor-cst',step:4},{label:'Medial frontal connections',lesson:'fat-language',step:0}],
  finding:{text:'Additional fictional examination: once prompted, the patient produces sustained force, but spontaneous initiation and alternating hand sequences are slower on the right. The examination is incomplete and no single mechanism has been established.',prompt:'Does this alter your interpretation of normal confrontation power? Explain what you would reconsider, what remains defensible, and what further findings could distinguish the alternatives.'},
  debrief:[
   {title:'Describe the distinction before assigning a label',text:'The new observation invites a distinction between initiating or sequencing an action and producing force once an action begins. It does not establish a syndrome. A useful conference response explains why the initial brief power examination did not settle the question.',sourceIds:[]},
   {title:'Use the medial anatomy as a reference',text:'Published SMA-region glioma cohorts describe postoperative motor and speech changes. They support discussing medial motor systems alongside primary motor and descending pathways. They do not establish the cause of this fictional preoperative finding or predict this individual’s recovery.',sourceIds:['sma']},
   {title:'Keep the alternatives visible',text:'For this exercise, state what additional examination and imaging would help distinguish initiation difficulty from weakness or other causes of slowed performance. Do not turn the schematic separation from area 4 into evidence that subcortical or vascular relationships are preserved.',sourceIds:[]},
   {title:'A defensible response',text:'“The brief strength examination is reassuring about the task tested, but it does not resolve the reported initiation difficulty. I would describe the medial frontal relationships, examine initiation and sequencing more closely, and keep the deep margin and individual functional organization explicitly unresolved.” This is an example of reasoning, not the only acceptable wording.',sourceIds:[]},
  ],
  rubric:rubric('Did I distinguish the medial premotor references, area 4 and descending pathways?','Did I separate an observation from a diagnosis and consider competing explanations?','Did I name specific missing examination and individual imaging information?','Did I avoid declaring functional sparing or forecasting recovery from an atlas?'),
  decision:{"question":"Power is full on confrontation testing. Once prompted, the patient produces sustained force, but spontaneous initiation and alternating hand sequences are slower on the right. Which inference best fits the evidence so far?","options":[{"id":"power-settles-it","label":"Normal confrontation power shows the motor system is not involved","rationale":"It correctly credits the brief power examination for the task it tested. It overlooks that initiation and sequencing are different observations from force, and that published SMA-region glioma cohorts describe postoperative motor and speech changes, a reason to keep medial motor systems in the discussion.","sourceIds":["sma"]},{"id":"characterize-first","label":"Initiation and sequencing are a separate, still uncharacterized observation; no mechanism can be named yet","rationale":"This is probably the most defensible step: it keeps the observation distinct from a diagnosis and names the missing examination. Its limit is that a closer bedside examination alone still leaves the deep margin and individual functional organization unresolved.","sourceIds":[]},{"id":"label-sma","label":"Attribute the slowing to supplementary motor area involvement","rationale":"It rightly brings medial motor systems into the discussion. It overreaches because the cited cohort describes postoperative associations; it does not diagnose a preoperative symptom, and slowed performance still has competing explanations the incomplete examination has not excluded.","sourceIds":["sma"]},{"id":"atlas-spares-cst","label":"Use the schematic distance from area 4 to infer a spared descending pathway","rationale":"It correctly separates the medial focus from primary motor cortex on the concept diagram. It overlooks that the vignette describes a location, not a registered volume, and a schematic separation cannot establish that subcortical or vascular relationships are preserved.","sourceIds":[]}]},
  sources:[source('sma','Resection of supplementary motor area gliomas: revisiting supplementary motor syndrome and the role of the frontal aslant tract','34598138','Retrospective surgical cohort. Postoperative associations do not diagnose preoperative symptoms or provide an individual probability of deficit.')],
 },
 {
  id:'insular',fictional:true,title:'The invisible part of the margin',location:'Insular glioma',number:'02',
  summary:'Account for a vascular relationship that the tract display cannot answer.',
  diagram:{label:'Left insular territory',view:'Lateral projection, opercula omitted',cx:265,cy:185,description:'A projected insular focus. Overlying opercula are omitted for the concept diagram. No vessel course, tumor boundary or safe corridor is encoded.'},
  vignette:'A 39-year-old adult with seizures is being discussed for a presumed left insular glioma. The fictional imaging summary describes a predominantly insular abnormality with a medial component. Everyday conversation and a brief limb examination are unremarkable. There is no complete language assessment or vessel-specific description in the referral.',
  known:['The abnormality is described as insular with medial extension.','No individual vessel reconstruction or intraoperative functional measurements are supplied.','The displayed atlas contains reference tracts and gross deep structures, not the patient’s vascular anatomy.'],
  unknown:['The relationship between the medial component and perforating vessels.','Detailed language findings and individual functional organization.','The lesion’s relationship to deep white matter and the central core.'],
  prompt:'A tract rendering appears to leave a gap along the medial side. How would you explain why that picture alone cannot define a safe margin?',
  explore:['Follow the insula toward the central core; distinguish a named layer from an installed rendered object.','Identify which important relationships remain absent from the display, especially vascular ones.'],
  references:[{label:'Insula and central core',lesson:'interoception',step:1},{label:'Layered relationships',lesson:'interoception',step:2}],
  finding:{text:'The next fictional report states that a vascular review cannot confidently establish whether the medial component remains lateral to the lenticulostriate vessels. The colleague’s proposed “gap” came from sampled tractography and did not include vessels.',prompt:'Revise or defend your margin argument. Separate “not shown”, “not assessed” and “shown to be absent”. What would you ask the conference to clarify?'},
  debrief:[
   {title:'Treat an absent layer as missing evidence',text:'The source display never contained the vascular relationship under discussion. A visible gap between sampled tracts therefore cannot answer the vessel question. The new report identifies uncertainty; it does not prove encasement or a particular operative endpoint.',sourceIds:[]},
   {title:'Connect the anatomical and clinical evidence',text:'Microsurgical studies describe insular arterial relationships. A clinical insular-glioma series specifically examined tumor position relative to lenticulostriate arteries. These are reasons to discuss vascular anatomy independently of tract display; neither makes this reference atlas a patient-specific margin map.',sourceIds:['insula-anatomy','lsa']},
   {title:'Make the request concrete',text:'For this exercise, identify which individual imaging, functional assessment and vessel relationships are missing. Keep cortical, white-matter and vascular evidence distinct. A well-calibrated response can retain the anatomical hypothesis while withdrawing an unsupported safety conclusion.',sourceIds:[]},
   {title:'A defensible response',text:'“The apparent tract gap is a property of the reconstruction shown. The medial vessel relationship is unresolved, so I cannot translate that gap into a margin. I would explicitly ask the team to characterize the missing vascular and deep anatomical relationships and correlate them with the wider functional assessment.”',sourceIds:[]},
  ],
  rubric:rubric('Did I relate the insula, deep white matter and central core without inventing a displayed vascular layer?','Did I distinguish a tract-display limitation from an established anatomical finding?','Did I identify the unresolved perforator relationship and functional assessment?','Did I avoid treating absent streamlines as clearance or uncertainty as proven encasement?'),
  decision:{"question":"The tract rendering shows a medial gap, but the vascular review cannot establish whether the medial component remains lateral to the lenticulostriate vessels. What can the conference defensibly infer?","options":[{"id":"gap-is-margin","label":"The tract gap indicates a clear medial margin","rationale":"It reads the rendering accurately as a gap between sampled streamlines. It overlooks that the display never contained vessels, while microsurgical anatomy describes insular arterial relationships that are reasons to discuss vascular anatomy independently. \"Not shown\" is not \"shown to be absent\".","sourceIds":["insula-anatomy"]},{"id":"unresolved-request","label":"The vessel relationship is unresolved; the tract gap cannot answer it","rationale":"This is probably the best-calibrated inference: it separates tract, vascular and functional evidence, and a clinical series examined tumor position relative to lenticulostriate arteries as its own question. Its limit is that it withdraws a safety claim without yet supplying the missing evidence.","sourceIds":["insula-anatomy","lsa"]},{"id":"uncertain-is-encased","label":"The uncertain vascular report means the vessels are encased","rationale":"It takes the vascular question seriously and does not rely on the tract display. It overreaches by converting \"not assessed confidently\" into a positive finding; the report identifies uncertainty and does not prove encasement or any particular endpoint.","sourceIds":[]}]},
  sources:[source('insula-anatomy','Tanriover et al. · Microsurgical anatomy of the insula and sylvian fissure','15137609','Human microsurgical anatomy study. Vascular descriptions support orientation, not universal operative distances.'),source('lsa','Resection of insular gliomas: importance of lenticulostriate artery position','18976071','Clinical series relating tumor and artery position. Its individual imaging is not installed in this atlas.')],
 },
 {
  id:'temporoparietal',fictional:true,title:'Beyond a fluent conversation',location:'Temporoparietal glioma',number:'03',
  summary:'Distinguish language tasks and keep visual pathways in the discussion.',
  diagram:{label:'Left posterior temporal / parietal territory',view:'Lateral concept diagram',cx:365,cy:190,description:'An illustrative posterior temporal/parietal focus. It is not an MRI, retinotopic map or depiction of tract displacement.'},
  vignette:'A 52-year-old adult is referred with seizures and a presumed left posterior temporal glioma extending toward inferior parietal white matter. The patient speaks fluently during a brief conversation. No structured language profile or formal visual-field assessment accompanies the referral.',
  known:['Conversational fluency was observed during a short encounter.','The location is described in words; there are no individual functional maps.','The atlas references illustrate language-route hypotheses and visual-pathway anatomy separately.'],
  unknown:['Performance across naming, repetition and comprehension tasks.','Formal visual-field findings.','Individual tumor, cortex and white-matter relationships.'],
  prompt:'The referral describes language as “intact”. What does the reported observation actually establish, and what would you want characterized before presenting the functional relationships?',
  explore:['Compare dorsal and ventral language references. Explain which task each cited experiment investigated.','Inspect the optic-radiation lesson as a separate relationship; do not infer a visual field from the fictional lesion symbol.'],
  references:[{label:'Dorsal language routes',lesson:'language-networks',step:1},{label:'Ventral language routes',lesson:'language-networks',step:2},{label:'Optic-radiation relationships',lesson:'optic-radiation',step:1}],
  finding:{text:'Additional fictional testing reports disproportionate difficulty repeating unfamiliar sound sequences, with better performance on the sampled single-word comprehension tasks. Formal visual-field testing is still unavailable. This is a limited task profile, not an isolated-tract diagnosis.',prompt:'How does the task profile change the conference discussion? State both the pathway hypothesis it may motivate and the conclusions it cannot support.'},
  debrief:[
   {title:'Replace the global label with the measured tasks',text:'Fluent conversation and performance on a structured repetition task are different observations. The new information makes the phrase “language intact” insufficiently specific. It does not establish that any other language function is normal.',sourceIds:[]},
   {title:'Use a pathway hypothesis, not a tract diagnosis',text:'Saur and colleagues combined task fMRI and tractography to investigate repetition and comprehension routes. Their task-based dorsal/ventral account offers a framework for discussion. It does not turn this fictional task profile into proof of an isolated fascicle lesion.',sourceIds:['language']},
   {title:'Keep vision as an independent unanswered question',text:'Work on temporal-resection cohorts combined tractography with visual-field outcomes and described variation in Meyer’s loop. It supports keeping visual function and individual anatomy in the assessment, not transferring a temporal-surgery risk estimate to this fictional temporoparietal case.',sourceIds:['vision']},
   {title:'A defensible response',text:'“Conversation was fluent, but the added testing identifies a task-specific difficulty that deserves a more precise language description. I would use dorsal and ventral references to frame hypotheses, correlate them with individual evidence, and keep the unassessed visual field explicit rather than inferring it from the schematic.”',sourceIds:[]},
  ],
  rubric:rubric('Did I discuss language pathways and visual pathways as distinct relationships?','Did I treat the task profile as a hypothesis-generating observation rather than a fascicle diagnosis?','Did I name missing language tasks, visual-field assessment and individual localization?','Did I avoid equating fluent conversation, parcel identity or template tracts with preserved function?'),
  decision:{"question":"Added testing shows disproportionate difficulty repeating unfamiliar sound sequences, better sampled single-word comprehension, and no formal visual-field test yet. Which inference best fits this limited task profile?","options":[{"id":"isolated-dorsal-lesion","label":"Diagnose an isolated dorsal-pathway fascicle lesion","rationale":"It uses the task profile to engage a pathway framework. It overreaches: the dorsal/ventral account comes from task fMRI and tractography and is task-dependent, so a limited profile motivates a hypothesis but does not prove an isolated fascicle lesion.","sourceIds":["language"]},{"id":"hypothesis-plus-vision","label":"Frame a dorsal-route hypothesis and keep the visual field an open question","rationale":"This is probably the most defensible inference: it replaces \"language intact\" with the measured tasks and keeps vision as an independent unanswered question. Its limit is that both the route hypothesis and the visual question still need individual evidence.","sourceIds":["language","vision"]},{"id":"field-from-diagram","label":"Infer the visual-field status from the lesion’s position on the diagram","rationale":"It rightly remembers that visual pathways are relevant here. It overlooks that Meyer’s loop varies between individuals in the cited cohorts, that source studied control and temporal-resection cohorts, and that the diagram is not a retinotopic map or a registered image.","sourceIds":["vision"]},{"id":"comprehension-preserves-ventral","label":"Better single-word comprehension shows the ventral route is preserved","rationale":"It reads the comprehension result correctly. It overreaches: the sampled tasks are limited, and the Saur dorsal/ventral account is task-dependent, so a better score on sampled tasks does not establish a preserved route.","sourceIds":["language"]}]},
  sources:[
   source('language','Saur et al. · Ventral and dorsal pathways for language','19004769','Task fMRI and tractography. Functional route hypotheses are task-dependent and are not interchangeable with each named atlas bundle.'),
   source('vision','Yogarajah et al. · Defining Meyer’s loop: temporal-lobe resections, visual fields and tractography','19460796','Control and temporal-resection cohorts; anatomical variation and postoperative field outcomes. Not a study of this fictional tumor or its individual risk.'),
  ],
 },
 {
  id:'right-medial-frontal',fictional:true,title:'Potentials preserved, movement absent',location:'Right medial frontal glioma',number:'04',
  summary:'Explain a dense postoperative deficit that the monitored pathway did not predict.',
  diagram:{label:'Right medial frontal territory',view:'Medial concept diagram, right hemisphere',cx:215,cy:112,description:'An illustrative right medial frontal focus at the supplementary motor region, anterior to the paracentral motor territory. No cavity boundary, oedema extent or monitoring site is shown.'},
  vignette:'A 61-year-old adult is discussed on the first morning after resection of a presumed right medial frontal high-grade glioma centred on the supplementary motor region. Before surgery there were focal seizures and a mild slowing of the left hand that improved on dexamethasone. Motor-evoked potentials from the left arm and leg were monitored continuously and remained stable to closure. This morning the patient has a dense left hemiplegia, fails to explore left space at the bedside, and is dysarthric. The fictional postoperative report describes a cavity confined to the supplementary motor region and adjacent white matter, a small area of restricted diffusion under one millilitre away from the descending corridor, and more oedema than on the preoperative FLAIR.',
  known:['Motor-evoked potentials were stable throughout the procedure.','The deficit is dense and involves movement, spatial attention and articulation at once.','The report describes a small remote restriction and increased oedema; it does not measure the cavity against the cingulate sulcus or the dorsal premotor cortex.'],
  unknown:['Whether the patient can move the left limbs automatically, for example when yawning or startled, while unable to move on command.','Whether the deficit fluctuates hour to hour, and whether any seizure activity has been recorded.','Where the oedema sits relative to the descending, frontoparietal and medial frontal white matter, and whether venous drainage was disturbed.'],
  prompt:'A colleague says: “The potentials were stable to closure, so the corticospinal tract is intact and this must be a stroke.” Which parts of that inference can you support? Name at least two other mechanisms that produce a dense deficit with a preserved monitored pathway, and state what you would examine and order first.',
  explore:['Compare the medial premotor references with area 4 and follow the descending corridor. The monitored potential samples one projection pathway; it does not measure initiation or the medial frontal contribution to movement.','Inspect the connections between medial and lateral frontal cortex on the right. Initiation, articulation and spontaneous movement have medial frontal contributions in both hemispheres.','Inspect the right frontoparietal attention references. A right frontal lesion with white-matter oedema can disturb spatial exploration without a parietal lesion.','Keep the anterior cingulate and medial frontal cortex in view as a node whose loss impairs initiation across domains, before naming a network.'],
  references:[{label:'Medial motor surface and area 4',lesson:'motor-cst',step:1},{label:'A motor deficit at three levels',lesson:'motor-cst',step:9},{label:'Medial and lateral frontal connections',lesson:'fat-language',step:0},{label:'A right frontoparietal case as a network problem',lesson:'attention-networks',step:5},{label:'A behavioural change before its network',lesson:'salience-network',step:5}],
  finding:{text:'Additional fictional findings: when yawning and when startled, the patient produces brief movements of the left arm, but cannot initiate movement on command. Dexamethasone was restarted on the first day. At 96 hours the dysarthria and the neglect have improved markedly and the arm now reaches grade 2 to 3, intermittently, within the same examination. The cavity boundary relative to the cingulate sulcus and the dorsal premotor cortex is still unmeasured, and no EEG has been recorded.',prompt:'Does this change the mechanism you proposed? Separate what the time course supports, what the preserved potentials prove, and which alternatives still need a specific test. State the next examination, the next study and the next conversation with the family.'},
  debrief:[
   {title:'Say what the monitored pathway can and cannot tell you',text:'A stable motor-evoked potential argues against a structural corticospinal lesion under the conditions of monitoring at the time of recording. It says nothing about initiation, about the medial frontal contribution to movement, about spatial attention, or about oedema that develops after closure. In a large peri-Rolandic series, most early postoperative motor deficits occurred without any change in the potentials, and most of those recovered. Preserved potentials therefore do not make the deficit a stroke by exclusion; they narrow the structural hypothesis and leave the network hypothesis open.',sourceIds:['mep']},
   {title:'Read the deficit as a failure of initiation, not one pathway',text:'Contralateral akinesia that eases with automatic or emotional movement, reduced spontaneous speech or dysarthria, and, on the right, neglect are the described consequences of removing the supplementary motor region. The facilitation sign is the bedside finding that separates initiation failure from paralysis. A right medial frontal cavity inside a larger zone of white-matter oedema can involve descending, frontoparietal and medial frontal fibres together, which is why three symptoms can arise and recover as one.',sourceIds:['sma','sma-series','neglect']},
   {title:'Use the time course and the imaging together, and keep the alternatives testable',text:'A remote restriction under one millilitre cannot carry a dense hemiplegia. Multi-domain improvement within days of restarting dexamethasone, in the window in which its effect on peritumoural water is measurable, favours a reversible oedema-related mechanism. That reading is a hypothesis with consequences: examine for facilitation at every visit; if the level fluctuates from hour to hour rather than within an examination, obtain prolonged EEG for non-convulsive seizures; if recovery stalls, image the venous system; measure the cavity against the cingulate sulcus and the dorsal premotor cortex, because extension into those territories is what predicted long-term deficit in the series cited, not the resection volume. Do not taper the steroid until the examination plateaus, and assess recovery at three months with timed hand tasks and a neglect battery, not with a strength grade alone.',sourceIds:['steroid','mep']},
   {title:'A defensible response',text:'“The stable potentials make a structural corticospinal lesion unlikely, but they do not explain the deficit. Dense hemiplegia with facilitation, neglect and dysarthria after a right supplementary motor resection reads as an initiation failure of the medial frontal region within a larger, steroid-responsive white-matter lesion. I would document facilitation and a neglect battery today, keep the steroid until the examination plateaus, obtain prolonged EEG if the level fluctuates between examinations, measure the cavity against the cingulate and premotor cortex, and tell the family that recovery over weeks is expected but not guaranteed.” This is an example of reasoning, not the only acceptable wording.',sourceIds:[]},
  ],
  rubric:rubric('Did I distinguish the monitored projection pathway from the medial frontal, frontoparietal and cingulate relationships?','Did I keep stroke, initiation failure, oedema and seizure as separate, testable explanations?','Did I name the facilitation examination, the EEG criterion, the cavity measurement and the three-month functional assessment?','Did I avoid treating stable potentials as proof of an intact motor system, or a steroid response as proof of the mechanism?'),
  decision:{"question":"MEPs were stable to closure. The patient now moves the left arm briefly when yawning or startled but not on command; dexamethasone was restarted on day 1, and by 96 hours neglect and dysarthria have improved markedly and the arm reaches grade 2 to 3 intermittently. No EEG has been recorded and the cavity is unmeasured. Which interpretation does the evidence best support?","options":[{"id":"stable-mep-stroke","label":"Stable potentials exclude a corticospinal cause, so this is a stroke","rationale":"It correctly reads stable MEPs as arguing against a structural corticospinal lesion during monitoring. It overlooks that, a restriction under one millilitre, reported away from the descending corridor, does not readily explain a dense hemiplegia, and that in the cited series most early deficits occurred without any change in the potentials.","sourceIds":["mep"]},{"id":"initiation-oedema-hypothesis","label":"Medial frontal initiation failure within oedema, as a testable hypothesis","rationale":"This is probably the best-supported reading: facilitation, neglect and dysarthria match described supplementary motor syndrome features, and the multi-domain improvement falls in the window of measurable steroid effect on peritumoural water. Its limit is that seizure and venous alternatives still need specific tests.","sourceIds":["sma","sma-series","steroid"]},{"id":"steroid-proves-mechanism","label":"The response to dexamethasone proves an oedema mechanism","rationale":"It rightly uses the time course as evidence. It overreaches because the cited imaging study supports the timing argument, not a mechanism for any individual deficit; a steroid response is consistent with oedema but does not exclude the alternatives still untested.","sourceIds":["steroid"]},{"id":"separate-parietal-lesion","label":"The neglect implies a second, parietal lesion not yet imaged","rationale":"It takes the neglect seriously as a distinct finding. It overlooks that neglect is a described feature of right-sided supplementary motor syndrome in a small series, and that a disconnection account of neglect, drawn from a stroke cohort, makes a right frontal white-matter lesion a plausible explanation without a second parietal lesion.","sourceIds":["sma-series","neglect"]}]},
  sources:[
   source('mep','Giampiccolo et al. · Long-term motor deficit in brain tumour surgery with preserved intra-operative motor-evoked potentials','33615216','Single-centre peri-Rolandic series. Most early deficits occurred without a change in the potentials; long-term deficit related to resection extending into dorsal premotor and anterior cingulate territory. It is not an outcome prediction for this fictional patient.'),
   source('sma','Krainik et al. · Role of the supplementary motor area in motor deficit following medial frontal lobe surgery','11552019','Prospective functional MRI and clinical series. Describes the transient contralateral deficit after medial frontal resection; it does not provide an individual recovery timeline.'),
   source('sma-series','Bannur & Rajshekhar · Post operative supplementary motor area syndrome: clinical features and outcome','10912196','Small clinical series describing the syndrome, including neglect with right-sided lesions. Small numbers; features, not frequencies.'),
   source('neglect','He et al. · Breakdown of functional connectivity in frontoparietal networks underlies behavioral deficits in spatial neglect','17359924','Stroke cohort. Supports a disconnection account of neglect; it is not a tumour or oedema study.'),
   source('steroid','Bastin et al. · Effects of dexamethasone on cerebral perfusion and water diffusion in patients with high-grade glioma','16484419','Imaging study of the steroid effect on peritumoural water within days. It supports the timing argument, not a mechanism for any individual deficit.'),
  ],
 },
];

// Optional decision drill per case: {question, options:[{id,label,rationale,sourceIds:[...]}]}.
// 2–4 options; sourceIds may be empty, but every entry must name one of the case's own sources.
export const DECISION_OPTIONS={min:2,max:4};
const text=v=>typeof v==='string'&&v.trim().length>0;
export function validateDecision(c){
 if(c.decision===undefined)return true;
 const d=c.decision,where=`Case ${c.id} decision`;
 if(!d||typeof d!=='object')throw Error(`${where}: must be an object`);
 if(!text(d.question))throw Error(`${where}: question is required`);
 if(!Array.isArray(d.options)||d.options.length<DECISION_OPTIONS.min||d.options.length>DECISION_OPTIONS.max)throw Error(`${where}: needs ${DECISION_OPTIONS.min}–${DECISION_OPTIONS.max} options`);
 const sourceIds=new Set((c.sources||[]).map(s=>s.id)),seen=new Set();
 for(const o of d.options){
  if(!o||typeof o!=='object'||!text(o.id))throw Error(`${where}: every option needs an id`);
  if(seen.has(o.id))throw Error(`${where}: option id "${o.id}" repeats`);seen.add(o.id);
  if(!text(o.label)||!text(o.rationale))throw Error(`${where}: option "${o.id}" needs a label and a rationale`);
  if(!Array.isArray(o.sourceIds))throw Error(`${where}: option "${o.id}" sourceIds must be a list`);
  for(const s of o.sourceIds)if(!sourceIds.has(s))throw Error(`${where}: option "${o.id}" cites "${s}", which is not in this case's sources`);
 }
 return true;
}
for(const c of CASES)validateDecision(c);
